# Generated by Django 5.2.4 on 2026-04-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_admindoctor_is_approved_admindoctor_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('booking_confirmation', 'Booking Confirmation'), ('booking_pending', 'Booking Pending'), ('booking_rejected', 'Booking Rejected'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
